### ISSUE TITLE
SFTP does seem to browse files anymore on version 1.8.17

### ISSUE THREAD

**Issue by harrypower** [sveale/remote-edit#124]
-I just updated remote-edit to version 1.8.17 after i was promoted to do so by atom!
-I then tried to open some sftp stuff i was working on and found i could not browse past the folder the host was set up to start at!  ( error occurred when reading directory .... )
-I then removed all the hosts listed that i was using and reinstalled the remote-edit package!  I got the same results when i set up a new host!
-The browse host process starts ok and connects to sftp device and shows the file/folder list with no errors.  I can from this list select a file and this seems to work but as soon as i select a folder to browse to it i get the "error occurred when reading directory ..." message!
-For now the work around seems to be to make a host of the directory of the files i want to select but this means i will need to make many hosts to work on many remote files in many directories!

**Comment by sveale** [comment]
Are you using windows?

**Comment by harrypower** [comment]
Yes windows 7

**Comment by petersandor** [comment]
I have issues with browsing too. I can only look around in the root directory, as soon as I want to go to other dir I get this error (1.8.18 @ Win 7):

```
Error: (SSH) Channel open failure:  {reason: "CONNECT_FAILED", lang: "", stack: (...), message: "(SSH) Channel open failure: "}
```

**Comment by harrypower** [comment]
Version 1.8.18 on windows 7 did not fix the issue!  
I can not browse most times but rather i get the "Uncaught RangeError: Maximum call stack size exceeded"  Issue #126  or i can continue to browse some times.  Once i try to open a file i will always get this Issue #126 .  ( at least that has been my travel on this)
At this moment i can not use to retrieve any file from any remote sftp service !  
I have atom version 1.0.11 and again windows 7 with all the latest updates as of this writing!

**Comment by sveale** [comment]
Issue #126 should be resolved.
Give it a whirl and see if it solves the issues. I've tested it on win7 on my machine and it's working again.

**Comment by harrypower** [comment]
Yes It seems to work on my windows 7 machine!
You may know this already but it seems Atom has changed how apm is setup or
accessed now.  It seems they moved where apm is installed and windows path
variable is not configured now for this!
I figured this out by uninstalling atom and reinstalling it and finding apm
did not work anymore.  It seems atom did does not clean up all files after
an update so this is confusing because apm binaries seem to be in several
places.
Only one binary works however.  Anyways i finally fully removed atom and
then reinstalled it and then reinstalled your remote-edit vers 1.8.19 and
yes it connects to my sftp machines and transfers files!
Thank You  for the fix!  PKS

On Sun, Sep 13, 2015 at 11:46 AM, Sverre Aleksandersen <
notifications@github.com> wrote:

> Issue #126 <https://github.com/sveale/remote-edit/issues/126> should be
> resolved.
> Give it a whirl and see if it solves the issues. I've tested it on win7 on
> my machine and it's working again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sveale/remote-edit/issues/124#issuecomment-139899129>.
>



-- 
                \|||/
-----0oo---( o o )---oo0------
                (_)
From the hand of PKS

**Comment by sveale** [comment]
Good to hear :+1:

**Comment by petersandor** [comment]
I have still an issue with browsing on my Win 7 machine, I get the same error before and after the update: 
```
Error: (SSH) Channel open failure:  {reason: "CONNECT_FAILED", lang: "", stack: (...), message: "(SSH) Channel open failure: "}
```

Call stack is:
```
(anonymous function)    /C:/Users/admin/.atom/packages/remote-edit/lib/model/sftp-host.coffee:233
```

Any ideas? I have none :flushed:
